name: CI/CD - Build changed Docker services

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed services
        id: changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api-gateway:
              - 'services/api-gateway/**'
            auth-service:
              - 'services/auth-service/**'
            cart-service:
              - 'services/cart-service/**'
            delivery-service:
              - 'services/delivery-service/**'
            notification-service:
              - 'services/notification-service/**'
            order-service:
              - 'services/order-service/**'
            payment-service:
              - 'services/payment-service/**'
            restaurant-service:
              - 'services/restaurant-service/**'
            review-service:
              - 'services/review-service/**'
            user-service:
              - 'services/user-service/**'

  build-services:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed != '[]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}
    env:
      GIT_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: harukiraito/${{ matrix.service }}:${{ env.GIT_TAG }}
